server:
  servlet:
    context-path: /api
  port: 8090

---
#spring:
#  profiles:
#    default: local
#  application:
#    name: inner-circle-survey
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:43306/survey?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#        default_batch_fetch_size: 500

spring:
  profiles:
    default: local
  application:
    name: inner-circle-survey
  datasource:
    url: jdbc:h2:mem:test;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect