spring:
    application:
        name: survey

    # h2 db
    h2:
        console:
            enabled: true
            path: /h2-console

    # datasource
    datasource:
        url: jdbc:h2:mem:survey
        driver-class-name: org.h2.Driver
        username: sa
        password:

    # jpa
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
              format_sql: true

# log
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql: trace