server:
  servlet:
    context-path: /api
  port: 8080

---
spring:
  profiles:
    default: local
  application:
    name: inner-circle-survey
  datasource:
    url: jdbc:h2:mem:test;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect