spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  version: v1
  packages-to-scan: com.innercircle.survey.interfaces
  default-produces-media-type: application/json
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
