spring:
    application:
        name: survey

    # h2 db
    datasource:
        url: jdbc:h2:mem:survey
        driver-class-name: org.h2.Driver
        username: sa
        password:

# log
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql: trace