spring:
  application:
    name: survey

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:survey
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
