### 1. 설문조사 생성 API
POST http://localhost:8080/surveys HTTP/1.1
Content-Type: application/json

{
   "title": "설문명"
 , "description": "설문 설명"
 , "objects" : [
      {"type": "text", "description": "설명1", "title": "단답형", "isRequired": true}
    , {"type": "rich_text", "description": "설명2", "title": "장문형", "isRequired": true}
    , {"type": "radio", "description": "설명3", "title": "단일 선택 리스트", "elements": ["element", "element2"], "isRequired": false}
    , {"type": "check_box", "description": "설명4", "title": "다중 선택 리스트", "elements": ["element", "element2"], "isRequired": true}
  ]
}

### 2. 설문조사 수정 API
PATCH http://localhost:8080/surveys/1 HTTP/1.1
Content-Type: application/json

{
  "version" : "1"
 , "title": "설문명2"
 , "description": "설문 설명2"
 , "objects" : [
      {"type": "text", "description": "설명2", "title": "단답형1", "isRequired": true}
    , {"type": "rich_text", "description": "설명5", "title": "장문형3", "isRequired": true}
    , {"type": "check_box", "description": "설명4", "title": "다중 선택 리스트", "elements": ["element", "element2"], "isRequired": true}
    , {"type": "radio", "description": "설명3", "title": "단일 선택 리스트2", "elements": ["element", "element2"], "isRequired": false}
  ]
}

### 3. 설문조사 답변 제출 API
POST http://localhost:8080/surveys/1 HTTP/1.1
Content-Type: application/json

{
   "version": 1,
   "objects": [
      {"type": "text", "id": 1, "content": "단답형 답변"},
      {"type": "rich_text", "id": 2, "content": "장문형 답변"},
      {"type": "radio", "id": 3, "content": {"selected_element": "6"}},
      {"type": "check_box", "id": 4, "content": {"checked_elements": ["7", "8"]}}
   ]
}

