spring:
  application:
    name: survey-api

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
    api-docs:
      path: /openapi/v3/api-docs
    packagesToScan: com.innercircle.surveyapi
    pathToMatch: /**

logging:
  level:
    root: INFO
    com.innercircle.surveyapi.common.RequestLoggingAspect: INFO
    org:
      springframework:
        web: DEBUG